### ISSUE TITLE
faster? pixelflut server

### ISSUE THREAD

**Issue by fabi321** [bits0rcerer/wellenbrecher#1]
I just stumbled upon this server, and noticed the speed claim, but https://github.com/sbernauer/breakwater seems to be faster. On the newest benchmark, it's twice as fast as shoreline, compared to ~1.5x speedup of wellenbrecher compared to shoreline. I'd be interested to see direct comparisons between the two.

Disclosure: I partially worked on that server.

**Comment by bits0rcerer** [comment]
Hey, thank you for mentioning breakwater. You are right. A comparisons would be very interesting.

I found breakwater some days ago. But I was already on train to 37c3, so I had no machines for a benchmark.

In case you are at 37c3, feel free to call 3959 or visit us at https://37c3.c3nav.de/l/c:0:115.44:181.78/

**Comment by bits0rcerer** [comment]
I accept defeat (for now) :D
